import{cleanup,render,screen,waitFor}from'@testing-library/react';import{MemoryRouter}from'react-router-dom';import{afterEach,describe,expect,it,vi}from'vitest';import App from'./App';
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals()});
describe('衡策前端',()=>{
 it('API不可用时展示演示数据与完整组合字段',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));render(<MemoryRouter><App/></MemoryRouter>);expect((await screen.findAllByText('演示数据')).length).toBeGreaterThan(0);expect(screen.getByText('模型组合')).toBeInTheDocument();expect(screen.getAllByText('失效条件').length).toBeGreaterThan(0);expect(screen.getAllByText('保护价').length).toBeGreaterThan(0);expect(screen.getByText(/模型输出，不是模拟成交或真实持仓/)).toBeInTheDocument()});
 it('主要导航包含研究与模拟页面',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));render(<MemoryRouter><App/></MemoryRouter>);await screen.findAllByText('演示数据');for(const label of['市场温度','题材雷达','风险中心','回测实验','模拟组合','决策日志','设置'])expect(screen.getAllByText(label).length).toBeGreaterThan(0)});
 it('公开接口显示研究/模拟观察、非PIT和非生产边界',async()=>{const raw={as_of:'2026-07-07T16:10:00+08:00',provider:'akshare',quality:{freshness:'fresh',status:'healthy'},market:{regime:'震荡偏强',score:68,exposure_cap:.72,style:'成长占优',reasons:['市场广度改善'],components:{trend_breadth:76}},portfolio:[{symbol:'002050.SZ',name:'三花智控',theme:'机器人',action:'持有',target_weight:.2,current_weight:.18,entry_price:44.8,initial_stop:40.9,thesis:['趋势健康'],invalidation:'跌破结构',risk_notes:['事件风险'],model_version:'v1',data_timestamp:'2026-07-07'}],candidates:[],themes:[]};vi.stubGlobal('fetch',vi.fn().mockImplementation((url:string)=>Promise.resolve({ok:true,json:async()=>url.includes('/dashboard')?raw:url.includes('/decisions')?{items:[]}:{active:'akshare',providers:[{provider:'akshare',pit_verified:false,production_ready:false,warning:'网页接口未证明PIT、历史成分或商业授权'}]}})));render(<MemoryRouter><App/></MemoryRouter>);await waitFor(()=>expect(screen.getByText('公开接口原型')).toBeInTheDocument());expect(screen.getByText(/仅研究与模拟观察/)).toBeInTheDocument();expect(screen.getByText('未验证 PIT')).toBeInTheDocument();expect(screen.getByText('非生产数据')).toBeInTheDocument();expect(screen.getByText('三花智控')).toBeInTheDocument()});
 it.each([
  ['/market','68° 震荡偏强'],['/themes','追踪扩散，不追逐喧嚣'],['/risk','风险先于收益'],['/backtest','先证伪，再相信'],['/simulation','模拟净值 ¥1,000,000'],['/logs','决策日志'],['/settings','设置'],['/more','研究工作台'],['/stocks/002050','三花智控 · 持有']
 ])('路由 %s 可独立访问并提供实质内容',async(path,title)=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);expect(await screen.findByRole('heading',{level:1,name:title})).toBeInTheDocument()});
 it('首页区分市场仓位上限与模型实际现金',async()=>{const raw={as_of:'2026-07-07T16:10:00+08:00',provider:'licensed',cash_weight:.8,quality:{freshness:'fresh',status:'healthy'},market:{regime:'震荡偏弱',score:52,exposure_cap:.5,components:{}},portfolio:[],candidates:[],themes:[]};vi.stubGlobal('fetch',vi.fn().mockImplementation((url:string)=>Promise.resolve({ok:true,json:async()=>url.includes('/dashboard')?raw:url.includes('/decisions')?{items:[]}:url.includes('/simulation')?{daily_equity:[],simulated_positions:[],ledger:[]}:{active:'licensed',providers:[{provider:'licensed',pit_verified:true,production_ready:true}]}})));render(<MemoryRouter><App/></MemoryRouter>);expect(await screen.findByRole('heading',{level:1,name:/现金 80.0%/})).toBeInTheDocument();expect(screen.getByText('50%')).toBeInTheDocument();expect(screen.getAllByText('80.0%').length).toBeGreaterThan(0)});
 it('模拟页只展示实际撮合持仓，不把模型输出冒充成交',async()=>{const raw={as_of:'2026-07-07T16:10:00+08:00',provider:'licensed',cash_weight:.8,quality:{freshness:'fresh',status:'healthy'},market:{regime:'震荡偏强',score:68,exposure_cap:.5,components:{}},portfolio:[{symbol:'MODEL.SZ',name:'模型股票',theme:'测试',action:'待买',target_weight:.2,initial_weight:.1,entry_price:10,initial_stop:9,thesis:['模型证据'],invalidation:'跌破结构'}],candidates:[],themes:[],simulation:{matching_ready:true}};const simulation={simulated_account:{cash:800000,initial_capital:1000000},simulated_positions:[{symbol:'FILLED.SZ',shares:1000,avg_cost:12.3,updated_at:'2026-07-07T10:00:00+08:00'}],ledger:[],daily_equity:[{day:'2026-07-07',cash:800000,market_value:200000,equity:1000000,drawdown:0}]};vi.stubGlobal('fetch',vi.fn().mockImplementation((url:string)=>Promise.resolve({ok:true,json:async()=>url.includes('/dashboard')?raw:url.includes('/decisions')?{items:[]}:url.includes('/simulation')?simulation:{active:'licensed',providers:[{provider:'licensed',pit_verified:true,production_ready:true}]}})));render(<MemoryRouter initialEntries={['/simulation']}><App/></MemoryRouter>);expect(await screen.findByText('FILLED.SZ')).toBeInTheDocument();expect(screen.queryByText('模型股票')).not.toBeInTheDocument();expect(screen.getByText((_text,node)=>node?.classList.contains('simulation-banner')===true&&node.textContent?.includes('不把今日 1 只模型标的冒充成交')===true)).toBeInTheDocument()});
});
